'use strict';
const $=s=>document.querySelector(s),canvas=$('#scene'),ctx=canvas.getContext('2d');
const W=1280,H=720,assets={},motion={jump:{frames:36},run:{frames:79}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,p)=>a+(b-a)*p,ease=p=>p*p*(3-2*p);
const shuffle=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let rows=[],collected=[],current=-1,lane=1,camera=-1,state='loading',anim=null,clock=0,lastFrame=null,sound=true,audio;
let hazard=null,immune=false,playerX=640,playerY=515,playerScale=1,targetX=640,stage=0,dwell=0,gemX=640,gemY=350,phaseStart=0,retryHazard=null,held=0,repeatAt=0;
const chaseLanes=[0,2,0,2,1],laneX=l=>290+l*350;
let master=null,lastStep=0;
function unlockAudio(){if(!sound)return false;try{if(!audio){try{if(navigator.audioSession)navigator.audioSession.type='playback'}catch{}audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=.65;master.connect(audio.destination)}if(audio.state!=='running')audio.resume().catch(()=>{});return true}catch{return false}}
function tone(freq,dur=.16,type='sine',delay=0,endFreq=null){if(!unlockAudio())return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+dur);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.18,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g);g.connect(master);o.onended=()=>{o.disconnect();g.disconnect()};o.start(t);o.stop(t+dur+.02)}
function noise(dur=.25,level=.2,cutoff=1000){if(!unlockAudio())return;const t=audio.currentTime,buf=audio.createBuffer(1,Math.ceil(audio.sampleRate*dur),audio.sampleRate),data=buf.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const src=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();src.buffer=buf;filter.type='lowpass';filter.frequency.setValueAtTime(cutoff,t);filter.frequency.exponentialRampToValueAtTime(Math.max(90,cutoff*.3),t+dur);gain.gain.setValueAtTime(.001,t);gain.gain.exponentialRampToValueAtTime(level,t+.025);gain.gain.exponentialRampToValueAtTime(.001,t+dur);src.connect(filter);filter.connect(gain);gain.connect(master);src.onended=()=>{src.disconnect();filter.disconnect();gain.disconnect()};src.start(t);src.stop(t+dur)}
function fx(name){if(!sound)return;if(name==='jump'){noise(.16,.1,2200);tone(230,.25,'sine',0,760)}else if(name==='land'){noise(.14,.28,700);tone(125,.16,'sine',0,50)}else if(name==='duck'){noise(.2,.12,1600)}else if(name==='fire'){noise(.75,.3,3000);tone(160,.5,'triangle',0,60)}else if(name==='lava'){noise(.9,.25,650);[0,.15,.32,.53].forEach(d=>tone(150,.16,'sine',d,70))}else if(name==='crack'){noise(.55,.4,2600);tone(130,.45,'triangle',0,40)}else if(name==='pickup'){[660,880,1320].forEach((f,i)=>tone(f,.25,'sine',i*.09))}else if(name==='step'){noise(.08,.1,450)}}
function crouchFrame(){if(!hazard)return 20;const down=clamp((clock-hazard.actionAt)/350,0,1),rise=clamp((clock-hazard.start-2600)/650,0,1);return Math.floor(rise>0?mix(56,78,rise):mix(20,48,down))}

function makeRows(){let prev=1;return shuffle(Array.from({length:10},(_,i)=>(i+1)*4)).map(correct=>{const choices=[0,1,2].filter(l=>Math.abs(l-prev)<=1),good=choices[Math.floor(Math.random()*choices.length)];prev=good;const bad=shuffle(Array.from({length:43},(_,i)=>i+1).filter(n=>n%4!==0)).slice(0,2);return{good,nums:[0,1,2].map(i=>i===good?correct:bad.pop()),broken:-1}})}
function project(r,l,cam=camera){const d=r-cam,s=1/(1+Math.max(-.3,d)*.44);return{x:640+(l-1)*350*s,y:132+405*s,s}}
function hint(text){$('#hint').textContent=text}
function banner(text='',kind=''){const b=$('#warning');b.textContent=text;b.className=kind;b.classList.toggle('final-pickup',['gate_approach','gate_wait','gem_jump','exit'].includes(state));b.hidden=!text}
function hud(){ $('#count').textContent=immune?'防火衣已裝備':`${collected.length} / 10`;$('#dots').innerHTML=Array.from({length:10},(_,i)=>`<i class="${i<collected.length?'done':''}"></i>`).join('');$('#collection').innerHTML=Array.from({length:10},(_,i)=>(i+1)*4).map(n=>`<span class="${collected.includes(n)?'got':''}">${n}</span>`).join('')}
function controls(){const hazardOn=state==='hazard',moveOn=state==='chase',jumpOn=hazardOn||state==='suit_wait'||state==='gate_wait';$('#left').disabled=!moveOn;$('#right').disabled=!moveOn;$('#duck').disabled=!hazardOn;$('#up').disabled=!jumpOn;$('#up').textContent=state==='suit_wait'?'跳高攞防火衣':state==='gate_wait'?'跳高攞寶石':'跳起';$('#actions').classList.toggle('active',hazardOn||moveOn||jumpOn);$('#duck').classList.toggle('suggested',hazardOn&&hazard.kind==='fire');$('#up').classList.toggle('suggested',(hazardOn&&hazard.kind==='lava')||state==='suit_wait'||state==='gate_wait')}
function choices(){const root=$('#choices');root.replaceChildren();if(state==='ready'&&current<9){const r=current+1;rows[r].nums.forEach((n,l)=>{const p=project(r,l),b=document.createElement('button');b.className='stone-choice';b.setAttribute('aria-label',`第 ${r+1} 行，${['左','中','右'][l]}邊石頭：${n}`);b.textContent=n;b.style.left=(p.x-132*p.s)/W*100+'%';b.style.top=(p.y-64*p.s)/H*100+'%';b.style.width=264*p.s/W*100+'%';b.style.height=106*p.s/H*100+'%';b.onclick=()=>jumpStone(l);root.append(b)})}controls()}
function reset(){rows=makeRows();collected=[];current=-1;camera=-1;lane=1;state='ready';anim=null;hazard=null;immune=false;held=0;retryHazard=null;stage=0;dwell=0;playerX=targetX=640;playerY=515;playerScale=1;$('#overlay').classList.add('hidden');banner();hint('撳下一行嘅石頭，揀四嘅倍數！');hud();choices()}
function jumpStone(l){if(state!=='ready'||current>=9)return;state='stone_jump';anim={start:clock,from:lane,to:l,row:current+1,correct:rows[current+1].good===l};choices();fx('jump');hint('跳！')}
function startHazard(kind){state='hazard';hazard={kind,start:clock,action:null,jumpAt:null,checked:false};banner(kind==='fire'?'小心火球！準備踎低':'岩漿就嚟升高！準備跳','danger');hint('先睇提示，再撳右下角動作掣。');tone(260,.12,'triangle');tone(260,.12,'triangle',.3);choices()}
function action(kind){if(state==='hazard'&&!hazard.checked){if(hazard.action!==kind)hazard.actionAt=clock;hazard.action=kind;if(kind==='jump')hazard.jumpAt=Math.max(clock,hazard.start+1450);else hazard.jumpAt=null;hint(kind==='duck'?'踎低，等火球飛過！':'準備好，跳過岩漿！');if(kind==='duck')fx('duck');return}if(kind==='jump'&&state==='suit_wait'){state='suit_jump';phaseStart=clock;banner('跳高攞防火衣！','gold');choices();fx('jump')}else if(kind==='jump'&&state==='gate_wait'){state='gem_jump';phaseStart=clock;banner('攞住四方寶石！','safe');choices();fx('jump')}}
function move(dir){if(state!=='chase')return;const l=clamp(Math.round((targetX-290)/350)+dir,0,2);targetX=laneX(l)}
function beginSuit(){state='suit_wait';playerX=laneX(lane);playerY=515;playerScale=1;banner('前面冇路！跳高攞防火衣','gold');hint('最後一粒石頭喇！攞到防火衣先可以落岩漿。');choices()}
function lose(title,message,retry=null){state='lost';held=0;retryHazard=retry;banner();$('#resultTag').textContent='再試一次！';$('#resultTitle').textContent=title;$('#resultText').textContent=message;$('#again').textContent=retry?'再試呢個障礙':'由頭再玩';$('#overlay').classList.remove('hidden');choices()}
function win(){state='won';held=0;banner();$('#resultTag').textContent='任務完成';$('#resultTitle').textContent='成功攞寶石出門！';$('#resultText').textContent='你搵齊四嘅倍數、避過障礙，仲征服咗岩漿房！';$('#again').textContent='再玩一次';$('#overlay').classList.remove('hidden');choices();tone(660);tone(880,.2,'sine',.15);tone(1100,.4,'sine',.3)}
function update(dt){if(['chase','lava_enter','gate_approach','exit'].includes(state)&&clock-lastStep>280){lastStep=clock;fx('step')}
 if(state==='stone_jump'){const p=clamp((clock-anim.start)/1000,0,1);camera=current+ease(p);if(p===1){camera=anim.row;lane=anim.to;if(!anim.correct){rows[anim.row].broken=lane;state='fall';anim.start=clock;hint('石頭碎咗！');fx('crack')}else{current=anim.row;collected.push(rows[current].nums[lane]);hud();fx('land');tone(660);tone(880,.25,'sine',.12);if(current===9)beginSuit();else if([1,3,5,7].includes(current))startHazard(current%4===1?'fire':'lava');else{state='ready';hint('啱喇！再揀下一行嘅四嘅倍數。');choices()}}}}
 else if(state==='fall'&&clock-anim.start>=1100){lose('跌咗落深淵！',`${rows[anim.row].nums[anim.to]} 唔係四嘅倍數。呢行要揀 ${rows[anim.row].nums[rows[anim.row].good]}！`)}
 else if(state==='hazard'){const elapsed=clock-hazard.start;if(elapsed>=1200&&!hazard.sounded){hazard.sounded=true;fx(hazard.kind)}if(hazard.jumpAt!==null&&clock>=hazard.jumpAt&&!hazard.jumpSound){hazard.jumpSound=true;fx('jump')}if(elapsed<1200)banner(`${hazard.kind==='fire'?'火球嚟緊，踎低！':'岩漿嚟緊，跳起！'} ${((2200-elapsed)/1000).toFixed(1)} 秒`,'danger');else if(!hazard.checked)banner(hazard.kind==='fire'?'火球飛過嚟喇！踎低！':'岩漿升高喇！跳起！','danger');if(elapsed>=2200&&!hazard.checked){hazard.checked=true;const jumpHeight=hazard.jumpAt===null?0:Math.sin(clamp((clock-hazard.jumpAt)/1500,0,1)*Math.PI)*155;const avoided=immune||(hazard.kind==='fire'?hazard.action==='duck'&&clock-hazard.actionAt>=200:hazard.action==='jump'&&jumpHeight>55);if(!avoided){tone(110,.3,'sawtooth');lose(hazard.kind==='fire'?'火球撞中咗！':'岩漿升上嚟喇！',hazard.kind==='fire'?'見到火球提示，就撳「踎低」等佢飛過。':'見到岩漿提示，就撳「跳起」跳過熱浪。',hazard.kind);return}banner('避到喇！','safe');tone(780)}if(elapsed>=3300){state='ready';hazard=null;banner();hint('安全喇！繼續揀四嘅倍數。');choices()}}
 else if(state==='suit_jump'){const p=clamp((clock-phaseStart)/1500,0,1);if(p>=.45&&!immune){immune=true;hud();fx('pickup');banner('防火衣到手！火球、岩漿都唔怕！','safe')}if(p===1){state='lava_enter';phaseStart=clock;anim={fromX:playerX};hint('落岩漿，追住四方寶石！');choices()}}
 else if(state==='lava_enter'){const p=clamp((clock-phaseStart)/1400,0,1);playerX=mix(anim.fromX,640,ease(p));if(p===1){state='chase';stage=0;dwell=0;gemX=640;gemY=345;targetX=640;playerY=515;phaseStart=clock;banner('用左、右掣追住四方寶石！','safe');hint('著咗防火衣，踩岩漿、撞火球都冇事！');choices()}}
 else if(state==='chase'){if(held&&clock>=repeatAt){move(held);repeatAt=clock+550}const delta=targetX-playerX;playerX+=Math.sign(delta)*Math.min(Math.abs(delta),dt*.66);const goal=laneX(chaseLanes[stage]),gd=goal-gemX;gemX+=Math.sign(gd)*Math.min(Math.abs(gd),dt*.42);gemY=mix(gemY,345-stage*25,Math.min(1,dt*.004));playerY=mix(playerY,515-stage*37,Math.min(1,dt*.004));playerScale=1-stage*.045;if(Math.abs(playerX-gemX)<85&&Math.abs(gemX-goal)<10)dwell+=dt;else dwell=0;banner(`追住寶石！${stage+1} / 5`,'safe');if(dwell>=650){stage++;dwell=0;tone(750+stage*60);if(stage===5){state='gate_approach';phaseStart=clock;anim={fromX:playerX,fromY:playerY};held=0;banner('到門口喇！','safe');choices()}}}
 else if(state==='gate_approach'){const p=clamp((clock-phaseStart)/1400,0,1);playerX=mix(anim.fromX,640,ease(p));playerY=mix(anim.fromY,285,ease(p));playerScale=mix(.82,.75,p);gemX=mix(gemX,640,Math.min(1,dt*.01));gemY=mix(gemY,135,Math.min(1,dt*.005));if(p===1){state='gate_wait';banner('最後一跳！攞寶石先可以出門','gold');hint('撳「跳高攞寶石」！');choices()}}
 else if(state==='gem_jump'){const p=clamp((clock-phaseStart)/1500,0,1);if(p>=.45&&!anim.gemCaught){anim.gemCaught=true;fx('pickup');banner('寶石到手！出口打開！','safe')}if(p===1){state='exit';phaseStart=clock;hint('帶住寶石，跑出城堡！')}}
 else if(state==='exit'&&clock-phaseStart>=1700)win();
}
function sprite(name,x,y,w,h,glow=''){ctx.save();if(glow){ctx.shadowColor=glow;ctx.shadowBlur=22}ctx.drawImage(assets[name],x-w/2,y-h/2,w,h);ctx.restore()}
function drawNinja(x,y,s=1,mode='idle',phase=0,duck=false){ctx.save();ctx.translate(x,y);if(immune){ctx.shadowColor='#ffe36a';ctx.shadowBlur=24;ctx.strokeStyle='#ffe08a99';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,-54*s,55*s,80*s,0,0,Math.PI*2);ctx.stroke()}const dw=108*s,dh=144*s;let f=0;if(duck){f=crouchFrame();ctx.drawImage(assets.crouch,(f%8)*192,Math.floor(f/8)*256,192,256,-dw/2,-dh+5*s,dw,dh)}else if(mode!=='idle'){f=mode==='run'?Math.floor(clock/1000*24)%motion.run.frames:Math.min(35,Math.floor(clamp(phase,0,1)*36));ctx.drawImage(assets[mode],(f%8)*192,Math.floor(f/8)*256,192,256,-dw/2,-dh+5*s,dw,dh)}else ctx.drawImage(assets.idle,-dw/2,-dh+5*s,dw,dh);if(immune){ctx.shadowBlur=8;sprite('vest',0,-49*s,43*s,43*s,'#ffc65e')}ctx.restore()}
function drawRoom(){const finale=['lava_enter','chase','gate_approach','gate_wait','gem_jump','exit','won'].includes(state);if(finale){ctx.drawImage(assets.room,0,0,1280,590,0,0,W,H)}else ctx.drawImage(assets.room,0,0,W,H);ctx.fillStyle='#080e2025';ctx.fillRect(0,0,W,H)}
function drawStones(){if(['chase','gate_approach','gate_wait','gem_jump','exit','won'].includes(state))return;ctx.save();if(state==='lava_enter')ctx.globalAlpha=1-clamp((clock-phaseStart)/1400,0,1);for(let r=9;r>=Math.max(0,current-1);r--){for(let l=0;l<3;l++){const p=project(r,l);if(p.y>640)continue;ctx.save();if(r<current)ctx.globalAlpha*=.4;if(rows[r].broken===l){ctx.fillStyle='#03040c';ctx.beginPath();ctx.ellipse(p.x,p.y-8*p.s,128*p.s,44*p.s,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ff8d27';ctx.lineWidth=4*p.s;ctx.stroke()}else{if(r===current+1&&state==='ready'){ctx.shadowColor='#ffc25a';ctx.shadowBlur=18*p.s}ctx.drawImage(assets.stone,p.x-143*p.s,p.y-73*p.s,286*p.s,133*p.s);ctx.shadowBlur=0;ctx.font=`900 ${Math.max(13,44*p.s)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.strokeStyle='#151e2d';ctx.lineWidth=5*p.s;ctx.strokeText(rows[r].nums[l],p.x,p.y-15*p.s);ctx.fillStyle=r===current&&l===lane?'#a4ffe2':'#fff9dc';ctx.fillText(rows[r].nums[l],p.x,p.y-15*p.s)}ctx.restore()}}ctx.restore()}
function drawHazard(){if(state!=='hazard')return;const elapsed=clock-hazard.start,p=project(current,lane),travel=clamp((elapsed-1200)/1000,0,1);if(hazard.kind==='fire'){const depart=clamp((elapsed-2200)/650,0,1);const x=elapsed>2200?mix(p.x,-160,depart):mix(1190,p.x,travel);const y=mix(210,p.y-140,travel);sprite('fire',x,y,45+travel*21,45+travel*21,'#ff7938')}else{const rise=elapsed<1200?0:elapsed<2200?travel:1-clamp((elapsed-2400)/700,0,1);ctx.save();ctx.beginPath();ctx.rect(0,190,W,420);ctx.clip();ctx.globalAlpha=.8*rise;ctx.drawImage(assets.room,0,290,1280,285,0,570-100*rise,1280,200);ctx.restore();if(elapsed<1200){ctx.strokeStyle='#ffcb57';ctx.lineWidth=5;ctx.setLineDash([12,9]);ctx.beginPath();ctx.ellipse(p.x,p.y+25,150,40,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}}}
function drawFinalFlames(){if(!immune)return;for(let i=0;i<5;i++){const p=((clock*.00024+i*.22)%1),x=mix(1200-i*110,100+i*170,p),y=mix(220,580,p);sprite('fire',x,y,90,100)} }
function render(){ctx.clearRect(0,0,W,H);drawRoom();drawStones();drawFinalFlames();let p=project(current,lane);
 if(state==='stone_jump'){const f=clamp((clock-anim.start)/1000,0,1);p=project(current+f,mix(anim.from,anim.to,ease(f)));p.y-=Math.sin(f*Math.PI)*125;if(current===-1)p.y+=(1-f)*85;drawNinja(p.x,p.y-22,p.s,'jump',f)}
 else if(state==='fall'){const f=clamp((clock-anim.start)/1100,0,1);p=project(anim.row,lane);ctx.save();ctx.beginPath();ctx.rect(p.x-180,p.y-180,360,200);ctx.clip();ctx.globalAlpha=1-f;drawNinja(p.x,p.y-22+f*260,1-f*.75);ctx.restore()}
 else if(['suit_wait','suit_jump'].includes(state)){const f=state==='suit_jump'?clamp((clock-phaseStart)/1500,0,1):0;if(!immune)sprite('vest',playerX,260+Math.sin(clock/300)*7,95,95,'#ffdc5e');drawNinja(playerX,playerY-Math.sin(f*Math.PI)*190,1,state==='suit_jump'?'jump':'idle',f)}
 else if(['lava_enter','chase','gate_approach','gate_wait','gem_jump'].includes(state)){let y=playerY,mode=state==='gate_wait'?'idle':'run',f=0;if(state==='gem_jump'){f=clamp((clock-phaseStart)/1500,0,1);y-=Math.sin(f*Math.PI)*115;mode='jump'}if(state!=='lava_enter'&&!(state==='gem_jump'&&anim.gemCaught))sprite('gem',gemX,gemY+Math.sin(clock/250)*6,65,65,'#67eaff');drawNinja(playerX,y,playerScale,mode,f);if(state==='gem_jump'&&anim.gemCaught)sprite('gem',playerX+26,y-85,32,32,'#7cecff')}
 else if(state==='exit'){const f=clamp((clock-phaseStart)/1700,0,1);ctx.save();ctx.globalAlpha=1-f;drawNinja(640,mix(285,140,f),mix(.75,.25,f),'run');sprite('gem',662,mix(205,100,f),35*(1-f),35*(1-f));ctx.restore()}
 else if(!['lost','won','loading'].includes(state)){let duck=false,f=0,y=p.y-22+(current===-1?85:0);if(state==='hazard'&&hazard.action==='duck')duck=true;if(state==='hazard'&&hazard.jumpAt!==null&&clock>=hazard.jumpAt){f=clamp((clock-hazard.jumpAt)/1500,0,1);y-=Math.sin(f*Math.PI)*155}drawNinja(p.x,y,p.s,f>0&&f<1?'jump':'idle',f,duck)}
 drawHazard();for(let i=0;i<18;i++){ctx.globalAlpha=.25;ctx.fillStyle='#ffda85';ctx.beginPath();ctx.arc((i*173+Math.sin(clock/1800+i)*20)%W,620-((clock*.025+i*47)%340),2,0,7);ctx.fill()}ctx.globalAlpha=1;
}
function frame(t){if(lastFrame===null)lastFrame=t;const dt=document.hidden?0:Math.min(50,t-lastFrame);lastFrame=t;clock+=dt;update(dt);render();requestAnimationFrame(frame)}
$('#restart').onclick=()=>{tone(440);reset()};$('#again').onclick=()=>{tone(440);if(retryHazard){const kind=retryHazard;retryHazard=null;$('#overlay').classList.add('hidden');startHazard(kind)}else reset()};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent=`音效：${sound?'開':'關'}`;if(master)master.gain.setValueAtTime(sound?.65:0,audio.currentTime);if(sound)fx('pickup')};$('#testSound').onclick=()=>{unlockAudio();fx('land');tone(880,.2,'sine',.2)};
$('#duck').onclick=()=>action('duck');$('#up').onclick=()=>action('jump');
for(const [id,dir]of [['left',-1],['right',1]]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{if(state!=='chase')return;e.preventDefault();b.setPointerCapture(e.pointerId);held=dir;move(dir);repeatAt=clock+550});b.addEventListener('pointerup',()=>held=0);b.addEventListener('pointercancel',()=>held=0);b.addEventListener('lostpointercapture',()=>held=0);b.addEventListener('click',e=>{if(e.detail===0)move(dir)})}
document.addEventListener('keydown',e=>{if(e.repeat)return;if(['1','2','3'].includes(e.key)){e.preventDefault();jumpStone(Number(e.key)-1)}else if(e.code==='Space'||e.key==='ArrowUp'){e.preventDefault();action('jump')}else if(e.key==='ArrowDown'){e.preventDefault();action('duck')}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();held=e.key==='ArrowLeft'?-1:1;move(held);repeatAt=clock+550}});document.addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight'].includes(e.key))held=0});window.addEventListener('blur',()=>held=0);document.addEventListener('visibilitychange',()=>{lastFrame=null;held=0});
document.addEventListener('pointerdown',unlockAudio,{capture:true});document.addEventListener('keydown',unlockAudio,{capture:true});
Promise.all(['room','stone','idle','jump','run','crouch','vest','gem','fire'].map(name=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{assets[name]=im;resolve()};im.onerror=reject;im.src=name+(['room','stone'].includes(name)?'.png':'.webp')}))).then(()=>{$('#loading').remove();reset();requestAnimationFrame(frame)}).catch(()=>{$('#loading').textContent='圖片未載入，請重新整理再試。'});
